plate:
  material:
    name: "LightGrey"
    color: "0.7 0.7 0.7 1.0"
  mesh: tlt600/plate.stl
  max:
    x: 0.1000
    y: 0.1100
    z: 0.0150
  min:
    x: -0.1000
    y: -0.1100
    z: -0.0000
  mass: 1.0

base:
  material:
    name: "LightGrey"
    color: "0.7 0.7 0.7 1.0"
  mesh: tlt600/long/base.stl
  max:
    x: 0.0827
    y: 0.0827
    z: 0.5450
  min:
    x: -0.0827
    y: -0.0827
    z: 0.0150
  mass: 10.0
  offset: 0.015

lower:
  material:
    name: "LightGrey"
    color: "0.7 0.7 0.7 1.0"
  mesh: tlt600/long/lower.stl
  max:
    x: 0.0742
    y: 0.0742
    z: 0.8550
  min:
    x: -0.0742
    y: -0.0742
    z: 0.3220
  mass: 10.0
  offset: 0.0
  joint:
    limit:
      effort: 2000
      lower: 0.0
      upper: 0.15
      velocity: 0.088
    axis:
      xyz: "0 0 1"

upper:
  material:
    name: "LightGrey"
    color: "0.7 0.7 0.7 1.0"
  mesh: tlt600/long/upper.stl
  max:
    x: 0.0645
    y: 0.0645
    z: 1.1550
  min:
    x: -0.0645
    y: -0.0645
    z: 0.6150
  mass: 10.0
  offset: 0.0
  joint:
    limit:
      effort: 2000
      lower: 0.0
      upper: 0.15
      velocity: 0.088
    axis:
      xyz: "0 0 1"


