plate:
  material:
    name: "LightGrey"
    color: "0.7 0.7 0.7 1.0"
  mesh: tlt500/plate.stl
  max:
    x: 0.1000
    y: 0.1100
    z: 0.0150
  min:
    x: -0.1000
    y: -0.1100
    z: -0.0000
  mass: 1.0

base:
  material:
    name: "LightGrey"
    color: "0.7 0.7 0.7 1.0"
  mesh: tlt500/long/base.stl
  max:
    x: 0.0827
    y: 0.0827
    z: 0.4951
  min:
    x: -0.0827
    y: -0.0827
    z: 0.0151
  mass: 10.0
  offset: 0.0

lower:
  material:
    name: "LightGrey"
    color: "0.7 0.7 0.7 1.0"
  mesh: tlt500/long/lower.stl
  max:
    x: 0.0742
    y: 0.0742
    z: 0.7551
  min:
    x: -0.0742
    y: -0.0742
    z: 0.2721
  mass: 10.0
  offset: 0.0
  joint:
    limit:
      effort: 2000.0
      lower: 0.0
      upper: 0.25
      velocity: 0.025

upper:
  material:
    name: "LightGrey"
    color: "0.7 0.7 0.7 1.0"
  mesh: tlt500/long/upper.stl
  max:
    x: 0.0645
    y: 0.0645
    z: 1.0051
  min:
    x: -0.0645
    y: -0.0645
    z: 0.5151
  mass: 10.0
  offset: 0.0225
  joint:
    limit:
      effort: 2000.0
      lower: 0.0
      upper: 0.25
      velocity: 0.025


